
/**
* @typedef {object} options
* @property {(config: import('./videoProcessor.js').onConfigParam) => void } onConfig
* @property {(config: object) => void } onChunk
*/

/** 
 * @typedef {object} onReadyParam
 * @property {boolean} hasMoov
 * @property {number} duration
 * @property {number} timescale
 * @property {boolean} isFragmented
 * @property {number} fragment_duration
 * @property {boolean} isProgressive
 * @property {boolean} hasIOD
 * @property {string[]} brands
 * @property {string} created
 * @property {string} modified
 * @property {object[]} tracks
 * @property {number} tracks.id
 * @property {string} tracks.name
 * @property {} tracks.references
 * @property {string} tracks.created
 * @property {string} tracks.modified
 * @property {number} tracks.movie_duration
 * @property {number} tracks.movie_timescale
 * @property {number} tracks.layer
 * @property {number} tracks.alternate_group
 * @property {number} tracks.volume
 * @property {object} tracks.matrix
 * @property {number} tracks.matrix.0
 * @property {number} tracks.matrix.1
 * @property {number} tracks.matrix.2
 * @property {number} tracks.matrix.3
 * @property {number} tracks.matrix.4
 * @property {number} tracks.matrix.5
 * @property {number} tracks.matrix.6
 * @property {number} tracks.matrix.7
 * @property {number} tracks.matrix.8
 * @property {number} tracks.track_width
 * @property {number} tracks.track_height
 * @property {number} tracks.timescale
 * @property {number} tracks.duration
 * @property {number} tracks.samples_duration
 * @property {string} tracks.codec
 * @property {object} tracks.kind
 * @property {string} tracks.kind.schemeURI
 * @property {string} tracks.kind.value
 * @property {string} tracks.language
 * @property {number} tracks.nb_samples
 * @property {number} tracks.size
 * @property {null|number} tracks.bitrate
 * @property {string} tracks.type
 * @property {object} tracks.audio
 * @property {number} tracks.audio.sample_rate
 * @property {number} tracks.audio.channel_count
 * @property {number} tracks.audio.sample_size
 * @property {object} tracks.video
 * @property {number} tracks.video.width
 * @property {number} tracks.video.height
 * @property {object[]} audioTracks
 * @property {number} audioTracks.id
 * @property {string} audioTracks.name
 * @property {} audioTracks.references
 * @property {string} audioTracks.created
 * @property {string} audioTracks.modified
 * @property {number} audioTracks.movie_duration
 * @property {number} audioTracks.movie_timescale
 * @property {number} audioTracks.layer
 * @property {number} audioTracks.alternate_group
 * @property {number} audioTracks.volume
 * @property {object} audioTracks.matrix
 * @property {number} audioTracks.matrix.0
 * @property {number} audioTracks.matrix.1
 * @property {number} audioTracks.matrix.2
 * @property {number} audioTracks.matrix.3
 * @property {number} audioTracks.matrix.4
 * @property {number} audioTracks.matrix.5
 * @property {number} audioTracks.matrix.6
 * @property {number} audioTracks.matrix.7
 * @property {number} audioTracks.matrix.8
 * @property {number} audioTracks.track_width
 * @property {number} audioTracks.track_height
 * @property {number} audioTracks.timescale
 * @property {number} audioTracks.duration
 * @property {number} audioTracks.samples_duration
 * @property {string} audioTracks.codec
 * @property {object} audioTracks.kind
 * @property {string} audioTracks.kind.schemeURI
 * @property {string} audioTracks.kind.value
 * @property {string} audioTracks.language
 * @property {number} audioTracks.nb_samples
 * @property {number} audioTracks.size
 * @property {null} audioTracks.bitrate
 * @property {string} audioTracks.type
 * @property {object} audioTracks.audio
 * @property {number} audioTracks.audio.sample_rate
 * @property {number} audioTracks.audio.channel_count
 * @property {number} audioTracks.audio.sample_size
 * @property {videoTracks[]} videoTracks
 * @property {number} videoTracks.id
 * @property {string} videoTracks.name
 * @property {} videoTracks.references
 * @property {string} videoTracks.created
 * @property {string} videoTracks.modified
 * @property {number} videoTracks.movie_duration
 * @property {number} videoTracks.movie_timescale
 * @property {number} videoTracks.layer
 * @property {number} videoTracks.alternate_group
 * @property {number} videoTracks.volume
 * @property {object} videoTracks.matrix
 * @property {number} videoTracks.matrix.0
 * @property {number} videoTracks.matrix.1
 * @property {number} videoTracks.matrix.2
 * @property {number} videoTracks.matrix.3
 * @property {number} videoTracks.matrix.4
 * @property {number} videoTracks.matrix.5
 * @property {number} videoTracks.matrix.6
 * @property {number} videoTracks.matrix.7
 * @property {number} videoTracks.matrix.8
 * @property {number} videoTracks.track_width
 * @property {number} videoTracks.track_height
 * @property {number} videoTracks.timescale
 * @property {number} videoTracks.duration
 * @property {number} videoTracks.samples_duration
 * @property {string} videoTracks.codec
 * @property {object} videoTracks.kind
 * @property {string} videoTracks.kind.schemeURI
 * @property {string} videoTracks.kind.value
 * @property {string} videoTracks.language
 * @property {number} videoTracks.nb_samples
 * @property {number} videoTracks.size
 * @property {number} videoTracks.bitrate
 * @property {string} videoTracks.type
 * @property {object} videoTracks.video
 * @property {number} videoTracks.video.width
 * @property {number} videoTracks.video.height
 * @property {} subtitleTracks
 * @property {} metadataTracks
 * @property {} hintTracks
 * @property {object[]} otherTracks
 * @property {number} otherTracks.id
 * @property {string} otherTracks.name
 * @property {} otherTracks.references
 * @property {string} otherTracks.created
 * @property {string} otherTracks.modified
 * @property {number} otherTracks.movie_duration
 * @property {number} otherTracks.movie_timescale
 * @property {number} otherTracks.layer
 * @property {number} otherTracks.alternate_group
 * @property {number} otherTracks.volume
 * @property {object} otherTracks.matrix
 * @property {number} otherTracks.matrix.0
 * @property {number} otherTracks.matrix.1
 * @property {number} otherTracks.matrix.2
 * @property {number} otherTracks.matrix.3
 * @property {number} otherTracks.matrix.4
 * @property {number} otherTracks.matrix.5
 * @property {number} otherTracks.matrix.6
 * @property {number} otherTracks.matrix.7
 * @property {number} otherTracks.matrix.8
 * @property {number} otherTracks.track_width
 * @property {number} otherTracks.track_height
 * @property {number} otherTracks.timescale
 * @property {number} otherTracks.duration
 * @property {number} otherTracks.samples_duration
 * @property {string} otherTracks.codec
 * @property {object} otherTracks.kind
 * @property {string} otherTracks.kind.schemeURI
 * @property {string} otherTracks.kind.value
 * @property {string} otherTracks.language
 * @property {number} otherTracks.nb_samples
 * @property {number} otherTracks.size
 * @property {null} otherTracks.bitrate
 * @property {string} otherTracks.type
 * @property {string} mime
 */


/**
 * @typedef {object} videoTracks
 * @property {number} videoTracks.id
 * @property {string} videoTracks.name
 * @property {} videoTracks.references
 * @property {string} videoTracks.created
 * @property {string} videoTracks.modified
 * @property {number} videoTracks.movie_duration
 * @property {number} videoTracks.movie_timescale
 * @property {number} videoTracks.layer
 * @property {number} videoTracks.alternate_group
 * @property {number} videoTracks.volume
 * @property {object} videoTracks.matrix
 * @property {number} videoTracks.matrix.0
 * @property {number} videoTracks.matrix.1
 * @property {number} videoTracks.matrix.2
 * @property {number} videoTracks.matrix.3
 * @property {number} videoTracks.matrix.4
 * @property {number} videoTracks.matrix.5
 * @property {number} videoTracks.matrix.6
 * @property {number} videoTracks.matrix.7
 * @property {number} videoTracks.matrix.8
 * @property {number} videoTracks.track_width
 * @property {number} videoTracks.track_height
 * @property {number} videoTracks.timescale
 * @property {number} videoTracks.duration
 * @property {number} videoTracks.samples_duration
 * @property {string} videoTracks.codec
 * @property {object} videoTracks.kind
 * @property {string} videoTracks.kind.schemeURI
 * @property {string} videoTracks.kind.value
 * @property {string} videoTracks.language
 * @property {number} videoTracks.nb_samples
 * @property {number} videoTracks.size
 * @property {number} videoTracks.bitrate
 * @property {string} videoTracks.type
 * @property {object} videoTracks.video
 * @property {number} videoTracks.video.width
 * @property {number} videoTracks.video.height
 */

module.exports = {}
